/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;


/**
 *
 * @author pedro
 */
public class FrameUsuario extends javax.swing.JFrame {

    int nivel;
    boolean crear=false;
       boolean encontrado=false;

    public FrameUsuario() {
   
        initComponents();
        ButtonGroup bt=new ButtonGroup();
        bt.add(nivelcero);
        bt.add(niveluno);
        this.getContentPane().setBackground(new java.awt.Color(30,30,30));
        titulo.setForeground(new java.awt.Color(204,204,204));
    
botonregistrar.setEnabled(false);
  this.setLocationRelativeTo(null);
    
    }
    public void validar(){
        if(lusuario.getText().isEmpty())
        {
            campusuario.setText("*");
        }
        else
        {
            campusuario.setText("");
        }
               if(lcontraseña.getText().isEmpty())
        {
            campcontra.setText("*");
        }
        else
        {
            campcontra.setText("");
        }
          
                 if(lnombre.getText().isEmpty())
        {
            campnombre.setText("*");
        }
        else
        {
            campnombre.setText("");
        }
         if(lapellido.getText().isEmpty())
        {
            campapellido.setText("*");
        }
        else
        {
            campapellido.setText("");
        }
           
        
                   
                    
        if(lusuario.getText().isEmpty() || lcontraseña.getText().isEmpty() || lnombre.getText().isEmpty()||lapellido.getText().isEmpty() )
        {
            botonregistrar.setEnabled(false);
        }
        else
        {
            botonregistrar.setEnabled(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lcontraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lnombre = new javax.swing.JTextField();
        lapellido = new javax.swing.JTextField();
        lcorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonregistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        accion = new javax.swing.JTextField();
        nivelcero = new javax.swing.JRadioButton();
        niveluno = new javax.swing.JRadioButton();
        campusuario = new javax.swing.JLabel();
        campcontra = new javax.swing.JLabel();
        campnombre = new javax.swing.JLabel();
        campapellido = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GYM");

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        lusuario.setForeground(new java.awt.Color(0, 0, 0));
        lusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lusuarioKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/socios.png"))); // NOI18N
        jLabel1.setText("Usuario");

        lcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        lcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lcontraseñaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contraseña.png"))); // NOI18N
        jLabel2.setText("Contraseña");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/status.png"))); // NOI18N
        jLabel3.setText("Nivel Acceso");

        lnombre.setForeground(new java.awt.Color(0, 0, 0));
        lnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnombreKeyReleased(evt);
            }
        });

        lapellido.setForeground(new java.awt.Color(0, 0, 0));
        lapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lapellidoKeyReleased(evt);
            }
        });

        lcorreo.setForeground(new java.awt.Color(0, 0, 0));
        lcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lcorreoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic-username_97587.png"))); // NOI18N
        jLabel5.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic-username_97587.png"))); // NOI18N
        jLabel4.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/socialemailcircularbutton_80177 (1).png"))); // NOI18N
        jLabel6.setText("Correo");

        botonregistrar.setBackground(new java.awt.Color(0, 0, 0));
        botonregistrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonregistrar.setForeground(new java.awt.Color(204, 204, 204));
        botonregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/check_ok_accept_apply_1582.png"))); // NOI18N
        botonregistrar.setText("Registrar");
        botonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregistrarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        accion.setEditable(false);
        accion.setBackground(new java.awt.Color(25, 25, 25));
        accion.setForeground(new java.awt.Color(204, 204, 204));

        nivelcero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nivelcero.setForeground(new java.awt.Color(204, 204, 204));
        nivelcero.setText("0");

        niveluno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        niveluno.setForeground(new java.awt.Color(204, 204, 204));
        niveluno.setText("1");

        campusuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campusuario.setForeground(new java.awt.Color(255, 0, 0));

        campcontra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campcontra.setForeground(new java.awt.Color(255, 0, 0));

        campnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campnombre.setForeground(new java.awt.Color(255, 0, 0));

        campapellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campapellido.setForeground(new java.awt.Color(255, 0, 0));

        titulo.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 204, 204));
        titulo.setText("Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(accion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(nivelcero)
                        .addGap(29, 29, 29)
                        .addComponent(niveluno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(botonregistrar)))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campapellido)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                            .addComponent(campcontra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campusuario))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campcontra))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nivelcero)
                    .addComponent(niveluno))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campnombre))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campapellido))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     new ManejoLogin().Leer();
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregistrarActionPerformed

       ManejoUsuarios me=new ManejoUsuarios();
       String cor="";
       String usuario=lusuario.getText();
        String contra=new String(lcontraseña.getPassword());
         if(nivelcero.isSelected()){
         nivel=0;   
        }
        else{
         nivel=1;   
        }
       String nombre=lnombre.getText();
       String apellido=lapellido.getText();
      String nuevalinea="";
        if(lcorreo.getText().isEmpty()){
           cor="-"; 
        }
        else{
        cor=lusuario.getText();}
       
        try {

            if (crear==false)
            {
                me.GuardarDatos (usuario, contra, nivel, nombre, apellido,cor);
            }
            else
            {
                nuevalinea=(usuario + "; " + contra + "; " + nivel + "; " + nombre + "; " +apellido+"; "+cor);
                me.ModificarDatos(nuevalinea,usuario);
            }
      
           

        } // fin try
        
        catch (Exception e)
        {
            e.printStackTrace();
        }
         blanquear();
    }//GEN-LAST:event_botonregistrarActionPerformed

    private void lusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lusuarioKeyReleased
        // TODO add your handling code here:
   
                
        validar();
        String cod;
        boolean encontrado=false;

        cod=lusuario.getText();

        Scanner s;
        
        try {
            
            File f=new File("Usuarios.txt");
            
            if(!f.exists())
            {
                
                f.createNewFile();
            }
            s = new Scanner(f);
            //else
            
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        if(cod.equalsIgnoreCase((sl.next())))
                        {
                           String k=sl.next();
                            int nivelacceso=Integer.parseInt(sl.next());
                            if(nivelacceso==1)
                            {
                                niveluno.setSelected(true);
                            }
                            else
                            {
                                nivelcero.setSelected(true);
                            }
                            lnombre.setText(sl.next());
                            lapellido.setText(sl.next());
                            lcorreo.setText(sl.next());
                            
                            encontrado=true;
                            crear = true;
                            accion.setText("Modificando...");
                        }
                        else
                        {  //Salida.setText("Este registro no existe");
                            lcontraseña.setText("");
                           nivelcero.setSelected(false);
                           niveluno.setSelected(false);
                            lnombre.setText("");
                            lapellido.setText("");
                            lcorreo.setText("");
 
                            encontrado=false;
                            crear = false;
                            accion.setText("Creando...");
                        }
                    } // fin try
                    catch (Exception  e1)
                    {
                       // JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
                       
                    }
                } // fin while
            

            s.close();
        } // fin try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e);
        }
       
    }//GEN-LAST:event_lusuarioKeyReleased

    private void lcontraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lcontraseñaKeyReleased
 validar();        // TODO add your handling code here:
    }//GEN-LAST:event_lcontraseñaKeyReleased

    private void lnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnombreKeyReleased
 validar();        // TODO add your handling code here:
    }//GEN-LAST:event_lnombreKeyReleased

    private void lapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lapellidoKeyReleased
 validar();        // TODO add your handling code here:
    }//GEN-LAST:event_lapellidoKeyReleased

    private void lcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lcorreoKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_lcorreoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accion;
    private javax.swing.JButton botonregistrar;
    private javax.swing.JLabel campapellido;
    private javax.swing.JLabel campcontra;
    private javax.swing.JLabel campnombre;
    private javax.swing.JLabel campusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lapellido;
    private javax.swing.JPasswordField lcontraseña;
    private javax.swing.JTextField lcorreo;
    private javax.swing.JTextField lnombre;
    private javax.swing.JTextField lusuario;
    private javax.swing.JRadioButton nivelcero;
    private javax.swing.JRadioButton niveluno;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    
    public void blanquear()
    {
        lusuario.setText("");
        lcontraseña.setText("");
        nivelcero.setSelected(false);
        niveluno.setSelected(false);
        lnombre.setText("");
        lapellido.setText("");
        lcorreo.setText("");
    }
    
    }
    



