/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class FrameReversar extends javax.swing.JFrame {

    /**
     * Creates new form FrameReversar
     */
    public FrameReversar() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(30,30,30));
        titulo.setForeground(new java.awt.Color(204,204,204));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesreversar = new javax.swing.JTextField();
        anioreversar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonReversar = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        labelmes = new javax.swing.JLabel();
        labelaño = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 25, 25));

        mesreversar.setBackground(new java.awt.Color(204, 204, 204));
        mesreversar.setForeground(new java.awt.Color(0, 0, 0));
        mesreversar.setCaretColor(new java.awt.Color(0, 0, 0));
        mesreversar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mesreversarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesreversarKeyTyped(evt);
            }
        });

        anioreversar.setBackground(new java.awt.Color(204, 204, 204));
        anioreversar.setForeground(new java.awt.Color(0, 0, 0));
        anioreversar.setCaretColor(new java.awt.Color(0, 0, 0));
        anioreversar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anioreversarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioreversarKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Mes");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Año");

        botonReversar.setBackground(new java.awt.Color(25, 25, 25));
        botonReversar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        botonReversar.setForeground(new java.awt.Color(204, 204, 204));
        botonReversar.setText("Reversar");
        botonReversar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReversarActionPerformed(evt);
            }
        });

        BotonMenu.setBackground(new java.awt.Color(25, 25, 25));
        BotonMenu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        BotonMenu.setForeground(new java.awt.Color(204, 204, 204));
        BotonMenu.setText("Menu");
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 204, 204));
        titulo.setText("Reversar Cobros");

        labelmes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelmes.setForeground(new java.awt.Color(255, 0, 0));

        labelaño.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelaño.setForeground(new java.awt.Color(255, 0, 0));

        Limpiar.setBackground(new java.awt.Color(25, 25, 25));
        Limpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(204, 204, 204));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/retroceder-32.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Limpiar.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonMenu)
                    .addComponent(Limpiar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonReversar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anioreversar)
                            .addComponent(mesreversar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelaño, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelmes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mesreversar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(labelmes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(labelaño)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(anioreversar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonReversar)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limpiar)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonMenu)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReversarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReversarActionPerformed
        int mes,anio;
        boolean encontrado=false;
        String idclien="",cantidad="";
        mes=Integer.parseInt(mesreversar.getText());
        anio=Integer.parseInt(anioreversar.getText());

        Scanner s;
        try {
            File f=new File("Cobros.txt");
            
            
            s = new Scanner(f);
                while (s.hasNextLine())
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        String id=sl.next();
                        String dia=sl.next();
                        
                        
                        if(mes==Integer.parseInt(sl.next()) && anio==Integer.parseInt(sl.next()))
                        {
                            idclien=sl.next();
                            String concepto=sl.next();
                            cantidad=sl.next();
                            double cant=0;
                            String estado=sl.next();
                            String nlinea=(id+";"+dia+";"+mes+";"+anio+";"+idclien+";"+concepto+";"+cant+";"+estado);
                            ManejoCobrooo mco=new ManejoCobrooo();
                            mco.ModificarDatos2(nlinea, id);
                             
                            
                        }
                       
                    } // fin try
                    catch (Exception  e1)
                    {
                        System.out.println("Error al leer Archivo ");
                       
                    }
                } // fin while
            s.close();

        } // fin try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e);
        }
        
        try {
                                           
            File fi=new File("Clientes.txt");

           
            Scanner ss = new Scanner(fi);
            //else

            while (ss.hasNextLine() && !encontrado)
            {
                String lineaa = ss.nextLine();
                Scanner sa=new Scanner(lineaa);
                sa.useDelimiter("\\s*;\\s*");
                
                try {
                    int idc=Integer.parseInt(idclien);
                    int idarc=Integer.parseInt(sa.next());
                    System.out.println(idarc );
                    if(idc==idarc)
                    {             System.out.println("ola");

                      String q,w,e,r,t,y,u,i,o,p,z,x,c,b;
                      q= sa.next();
                      w= sa.next();
                      e= sa.next();
                      r= sa.next();
                      t= sa.next();
                      y= sa.next();
                      u= sa.next();
                      i= sa.next();
                      o= sa.next();
                      p= sa.next();
                      z= sa.next();
                      x= sa.next();
                      c= sa.next();
                      double v= Double.parseDouble(sa.next());
                      double cobro=Double.parseDouble(cantidad);
                      v= v-cobro;
                      b= sa.next();
                      String Nlinea=(idarc+";"+q+";"+w+";"+e+";"+r+";"+t+";"+y+";"+u+";"+i+";"+o+";"+p+";"+z+";"+x+";"+c+";"+v+";"+b);
                      ManejoClientes mc=new ManejoClientes();
                      mc.ModificarDatos(Nlinea, idclien);
                      encontrado=true;
                    }    
                } // fin try
                catch (Exception  e1)
                {
                    // JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);

                }
            } // fin while
            ss.close();

        } // fin try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e);
        }
       File fNuevo= new File("Clientes2.txt");
        File fAntiguo= new File("Clientes.txt");
        fAntiguo.delete();
        fNuevo.renameTo(fAntiguo); 
        File fNuevoo= new File("Cobros2.txt");
        File fAntiguoo= new File("Cobros.txt");
        fAntiguoo.delete();
        fNuevoo.renameTo(fAntiguoo); 
    }//GEN-LAST:event_botonReversarActionPerformed

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        new ManejoLogin().Leer();
        
        this.dispose();
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void mesreversarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesreversarKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_mesreversarKeyTyped

    private void anioreversarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioreversarKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_anioreversarKeyTyped

    private void mesreversarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesreversarKeyReleased
        // TODO add your handling code here:
        validar();
        int mes=Integer.parseInt(mesreversar.getText());
        if(mes<=0 || mes>12)
        {
            JOptionPane.showMessageDialog(this, "Mes incorrecto");
            mesreversar.setText("");
        }
     
   
    }//GEN-LAST:event_mesreversarKeyReleased

    private void anioreversarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioreversarKeyReleased
        // TODO add your handling code here:
        validar();
        int año=Integer.parseInt(anioreversar.getText());
        if(año<2021 )
        {
            labelaño.setText("*");
            botonReversar.setEnabled(false);
        }
        else
        {
            labelaño.setText("");
            
        }

    }//GEN-LAST:event_anioreversarKeyReleased

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
     mesreversar.setText("");
     anioreversar.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReversar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReversar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReversar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReversar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameReversar().setVisible(true);
            }
        });
    }


    public void validar()
    {
        if(mesreversar.getText().isEmpty())
        {
            labelmes.setText("*");
            
        }
        else
        {
            labelmes.setText("");
        }
        if(anioreversar.getText().isEmpty())
        {
            labelaño.setText("*");
        }
        else
        {
            labelaño.setText("");
        }
        if(mesreversar.getText().isEmpty()||anioreversar.getText().isEmpty())
        {
            botonReversar.setEnabled(false);
        }
        else
        {
            botonReversar.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField anioreversar;
    private javax.swing.JButton botonReversar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelaño;
    private javax.swing.JLabel labelmes;
    private javax.swing.JTextField mesreversar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
