/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class FrameSalas extends javax.swing.JFrame {
boolean encontrado;
    /**
     * Creates new form FrameSalas
     */
    public FrameSalas() {
        initComponents();
       this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idsala = new javax.swing.JTextField();
        nombresala = new javax.swing.JTextField();
        descripcionsala = new javax.swing.JTextField();
        localizacionsala = new javax.swing.JTextField();
        Botonsalas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        accion = new javax.swing.JTextPane();
        BOTONMENU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ID SALA");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE SALA");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("DESCRIPCION");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("ID LOCALIZACION SALA");

        idsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsalaActionPerformed(evt);
            }
        });
        idsala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idsalaKeyTyped(evt);
            }
        });

        nombresala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresalaActionPerformed(evt);
            }
        });

        localizacionsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizacionsalaActionPerformed(evt);
            }
        });
        localizacionsala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                localizacionsalaKeyTyped(evt);
            }
        });

        Botonsalas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Botonsalas.setText("ACEPTAR");
        Botonsalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonsalasActionPerformed(evt);
            }
        });

        accion.setEditable(false);
        accion.setOpaque(false);
        jScrollPane1.setViewportView(accion);

        BOTONMENU.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BOTONMENU.setText("MENU");
        BOTONMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONMENUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 457, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(Botonsalas)
                        .addGap(62, 62, 62)
                        .addComponent(BOTONMENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(63, 63, 63)))
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idsala, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(descripcionsala)
                                .addComponent(localizacionsala, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(nombresala)))))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(idsala, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombresala, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcionsala, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(localizacionsala, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOTONMENU)
                    .addComponent(Botonsalas))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresalaActionPerformed

    private void BotonsalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonsalasActionPerformed
        
String idsa=idsala.getText();
String nombre=nombresala.getText();
String descrip=descripcionsala.getText();
String local=localizacionsala.getText();
String msj;
ManejoSallas mn=new ManejoSallas();

try
{
    if(encontrado==false)
    {
       msj= mn.GuardarDatos(idsa,nombre,descrip,local);
    }
    else
    {
        mn.ModificarDatos(idsa,nombre,descrip,local);
    }
    accion.setText("Guardando datos");

    
    Blanquear();
                
    
    
    
}catch(IOException e)
{
    System.out.println("ERROR"+e);
} 
          
            if(idsala.getText().isEmpty())
  {
      JOptionPane.showMessageDialog(this, "ID SALA OBLIGATORIA ", "Campo en blanco", JOptionPane.INFORMATION_MESSAGE);
  }
                      
            if(nombresala.getText().isEmpty())
  {
      JOptionPane.showMessageDialog(this, "NOMBRE SALA OBLIGATORIO ", "Campo en blanco", JOptionPane.INFORMATION_MESSAGE);
  }
                      
            if(descripcionsala.getText().isEmpty())
  {
      JOptionPane.showMessageDialog(this, "DESCRIPCION OBLIGATORIA ", "Campo en blanco", JOptionPane.INFORMATION_MESSAGE);
  }
                      
            if(localizacionsala.getText().isEmpty())
  {
      JOptionPane.showMessageDialog(this, "ID LOCALIZACION OBLIGATORIA ", "Campo en blanco", JOptionPane.INFORMATION_MESSAGE);
  }


    
    }//GEN-LAST:event_BotonsalasActionPerformed

    private void idsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsalaActionPerformed
        // TODO add your handling code here:
         encontrado=false;
        ManejoSallas mn=new ManejoSallas();
        String idsa=idsala.getText();
        
        ArrayList<String> ArrayRetorno=new ArrayList<String>();
        try
        {
            ArrayRetorno=mn.LeerDatos(idsa);
            if(!ArrayRetorno.isEmpty()&&"1".equals(ArrayRetorno.get(0)))
                    {
                        encontrado=true;
                        nombresala.setText(ArrayRetorno.get(1));
                        descripcionsala.setText(ArrayRetorno.get(2));
                        localizacionsala.setText(ArrayRetorno.get(3));
                        accion.setText("Modificando");
                        
                    }
            else
            {
                nombresala.setText("");
                descripcionsala.setText("");
                localizacionsala.setText("");
                        accion.setText("Creando");
            }
        
                     
         }catch(UnsupportedEncodingException e)
        {
            System.out.println("ERROR" + e);
        }
        catch(IOException e)
        {
            System.out.println("ERROR" + e);
        }

    
        
    }//GEN-LAST:event_idsalaActionPerformed

    private void localizacionsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizacionsalaActionPerformed
        // TODO add your handling code here:
     encontrado = false;
 ManejoLocalizacion ml=new ManejoLocalizacion();
 String idlocal=localizacionsala.getText();
 ArrayList<String> retorno=new ArrayList<String>();
 
 try
 {
    retorno=ml.LeerDatos(idlocal);
    if(!retorno.isEmpty()&&"1".equals(retorno.get(0)))
    {
        encontrado=true;
        localizacionsala.setText(retorno.get(1));
        
        
    }
    else
    {
        localizacionsala.setText("");
    }
                
     
     
 }catch(Exception e)
 {
     System.out.println("ERROR"+e);
 }

    }//GEN-LAST:event_localizacionsalaActionPerformed

    private void idsalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idsalaKeyTyped
char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_idsalaKeyTyped

    private void localizacionsalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localizacionsalaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_localizacionsalaKeyTyped

    private void BOTONMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONMENUActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BOTONMENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSalas().setVisible(true);
            }
        });
        
    }
        public void Blanquear()
        {
            nombresala.setText("");
            descripcionsala.setText("");
            localizacionsala.setText("");
            
        }
        
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONMENU;
    private javax.swing.JButton Botonsalas;
    private javax.swing.JTextPane accion;
    private javax.swing.JTextField descripcionsala;
    private javax.swing.JTextField idsala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localizacionsala;
    private javax.swing.JTextField nombresala;
    // End of variables declaration//GEN-END:variables
}
