/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;


/**
 *
 * @author pedro
 */
public class FrameUsuario extends javax.swing.JFrame {

    private static Scanner leer;


    public FrameUsuario() {
       
        initComponents();
    
botonregistrar.setEnabled(false);
  this.setLocationRelativeTo(null);
    
    }
    public void validar(){
        if(lusuario.getText().isEmpty())
        {
            campusuario.setText("Campo Obligatorio");
        }
        else
        {
            campusuario.setText("");
        }
               if(lcontraseña.getText().isEmpty())
        {
            campcontra.setText("Campo Obligatorio");
        }
        else
        {
            campcontra.setText("");
        }
          if(lnivelacceso.getText().isEmpty())
        {
            campnivel.setText("Campo Obligatorio");
        }
        else
        {
            campnivel.setText("");
        }
                 if(lnombre.getText().isEmpty())
        {
            campnombre.setText("Campo Obligatorio");
        }
        else
        {
            campnombre.setText("");
        }
         if(lapellido.getText().isEmpty())
        {
            campapellido.setText("Campo Obligatorio");
        }
        else
        {
            campapellido.setText("");
        }
          if(!lcorreo.getText().contains("@") || !lcorreo.getText().contains("."))
                 {
                            campcorreo.setText("Correo Invalido");
                            botonregistrar.setEnabled(false);
                  }
              else
                        {
                            campcorreo.setText("");
                            
                        }
                                    
        
                   
                    
        if(lusuario.getText().isEmpty() || lcontraseña.getText().isEmpty() || lnivelacceso.getText().isEmpty()||lnombre.getText().isEmpty()||lapellido.getText().isEmpty() )
        {
            botonregistrar.setEnabled(false);
        }
        else
        {
            botonregistrar.setEnabled(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lcontraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lnivelacceso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnombre = new javax.swing.JTextField();
        lapellido = new javax.swing.JTextField();
        lcorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonregistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        campusuario = new javax.swing.JLabel();
        campcontra = new javax.swing.JLabel();
        campnivel = new javax.swing.JLabel();
        campnombre = new javax.swing.JLabel();
        campapellido = new javax.swing.JLabel();
        campcorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lusuarioKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Usuario");

        lcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lcontraseñaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");

        lnivelacceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnivelaccesoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnivelaccesoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nivel Acceso");

        lnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnombreKeyReleased(evt);
            }
        });

        lapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lapellidoKeyReleased(evt);
            }
        });

        lcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lcorreoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Correo");

        botonregistrar.setText("Registrar");
        botonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregistrarActionPerformed(evt);
            }
        });

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campusuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campusuario.setForeground(new java.awt.Color(255, 0, 0));

        campcontra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campcontra.setForeground(new java.awt.Color(255, 0, 0));

        campnivel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campnivel.setForeground(new java.awt.Color(255, 0, 0));

        campnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campnombre.setForeground(new java.awt.Color(255, 0, 0));

        campapellido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campapellido.setForeground(new java.awt.Color(255, 0, 0));

        campcorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campcorreo.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(lusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel3)
                                .addGap(90, 90, 90)
                                .addComponent(lnivelacceso, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel4)
                                .addGap(41, 41, 41)
                                .addComponent(lnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)
                                .addComponent(lapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campapellido)
                            .addComponent(campnombre)
                            .addComponent(campnivel)
                            .addComponent(campcontra)
                            .addComponent(campusuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(botonregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(lcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(campcorreo)))
                .addGap(170, 170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campusuario)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(lcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campcontra))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lnivelacceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campnivel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campnombre)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campapellido)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu m =new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregistrarActionPerformed

        File archivo;
        FileWriter escribir;
        PrintWriter linea;

        int nivel;
        nivel=Integer.parseInt(lnivelacceso.getText());
 
        archivo=new File("Usuarios.txt");
        if(!archivo.exists())
        {
            try {
                archivo.createNewFile();
                escribir=new FileWriter(archivo,true);
                String us=lusuario.getText();
                String Pass=new String(lcontraseña.getPassword());
                linea=new PrintWriter(escribir);
                linea.print(us+";");
                linea.print(Pass+";");
                if(nivel<0 || nivel>1)
                {

                    JOptionPane.showInputDialog( "Ingrese el acceso correcto");

                }
                linea.print(nivel+";");

                linea.print(lnombre.getText()+";");
                linea.print(lapellido.getText()+";");
                linea.print(lcorreo.getText()+"\n");
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(FrameUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else
        {
            try {

                escribir=new FileWriter(archivo,true);
                linea=new PrintWriter(escribir);
                linea.print(lusuario.getText()+";");
                String contraa=new String(lcontraseña.getPassword());
                linea.print((contraa+";"));
                linea.print(nivel+";");
                linea.print(lnombre.getText()+";");
                linea.print(lapellido.getText()+";");
                linea.print(lcorreo.getText()+"\n");
                linea.close();
                escribir.close();
                
            
            
            
  
        }catch (IOException ex) {
                Logger.getLogger(FrameUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        }
blanquear();
    }//GEN-LAST:event_botonregistrarActionPerformed

    private void lnivelaccesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnivelaccesoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0'|| c>'1')evt.consume();
        if(lnivelacceso.getText().length()>=1)evt.consume();
    }//GEN-LAST:event_lnivelaccesoKeyTyped

    private void lusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lusuarioKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_lusuarioKeyReleased

    private void lcontraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lcontraseñaKeyReleased
 validar();        // TODO add your handling code here:
    }//GEN-LAST:event_lcontraseñaKeyReleased

    private void lnivelaccesoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnivelaccesoKeyReleased
 validar();        // TODO add your handling code here:
    }//GEN-LAST:event_lnivelaccesoKeyReleased

    private void lnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnombreKeyReleased
 validar();        // TODO add your handling code here:
    }//GEN-LAST:event_lnombreKeyReleased

    private void lapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lapellidoKeyReleased
 validar();        // TODO add your handling code here:
    }//GEN-LAST:event_lapellidoKeyReleased

    private void lcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lcorreoKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_lcorreoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonregistrar;
    private javax.swing.JLabel campapellido;
    private javax.swing.JLabel campcontra;
    private javax.swing.JLabel campcorreo;
    private javax.swing.JLabel campnivel;
    private javax.swing.JLabel campnombre;
    private javax.swing.JLabel campusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lapellido;
    private javax.swing.JPasswordField lcontraseña;
    private javax.swing.JTextField lcorreo;
    private javax.swing.JTextField lnivelacceso;
    private javax.swing.JTextField lnombre;
    private javax.swing.JTextField lusuario;
    // End of variables declaration//GEN-END:variables

    
    public void blanquear()
    {
        lusuario.setText("");
        lcontraseña.setText("");
        lnivelacceso.setText("");
        lnombre.setText("");
        lapellido.setText("");
        lcorreo.setText("");
    }
    
    }
    



