/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class FrameSalas extends javax.swing.JFrame {
boolean encontrado=false;
boolean crear=false;
    /**
     * Creates new form FrameSalas
     */
    public FrameSalas() {
        initComponents();
        botonaceptar.setEnabled(false);
       this.setLocationRelativeTo(null);
        
    }
public void validar()
{
     if(idsala.getText().isEmpty())
        {
            campsala.setText("Campo Obligatorio");
        }
        else
        {
            campsala.setText("");
        }
      if(nombresala.getText().isEmpty())
        {
            campnombre.setText("Campo Obligatorio");
        }
        else
        {
            campnombre.setText("");
        }
       if(descripcionsala.getText().isEmpty())
        {
            campdescrip.setText("Campo Obligatorio");
        }
        else
        {
            campdescrip.setText("");
        }
        if(localizacionsala.getText().isEmpty())
        {
            camplocal.setText("Campo Obligatorio");
        }
        else
        {
            camplocal.setText("");
        }
        
        if(idsala.getText().isEmpty() || nombresala.getText().isEmpty()||descripcionsala.getText().isEmpty()||localizacionsala.getText().isEmpty())
        {
            botonaceptar.setEnabled(false);
        }
        else
        {
            botonaceptar.setEnabled(true);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idsala = new javax.swing.JTextField();
        nombresala = new javax.swing.JTextField();
        descripcionsala = new javax.swing.JTextField();
        localizacionsala = new javax.swing.JTextField();
        botonaceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        accion = new javax.swing.JTextPane();
        BOTONMENU = new javax.swing.JButton();
        campsala = new javax.swing.JLabel();
        campnombre = new javax.swing.JLabel();
        campdescrip = new javax.swing.JLabel();
        camplocal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ID SALA");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE SALA");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("DESCRIPCION");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("ID LOCALIZACION SALA");

        idsala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idsalaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idsalaKeyTyped(evt);
            }
        });

        nombresala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresalaActionPerformed(evt);
            }
        });
        nombresala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombresalaKeyReleased(evt);
            }
        });

        descripcionsala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcionsalaKeyReleased(evt);
            }
        });

        localizacionsala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                localizacionsalaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                localizacionsalaKeyTyped(evt);
            }
        });

        botonaceptar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonaceptar.setText("ACEPTAR");
        botonaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonaceptarActionPerformed(evt);
            }
        });

        accion.setEditable(false);
        accion.setOpaque(false);
        jScrollPane1.setViewportView(accion);

        BOTONMENU.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BOTONMENU.setText("MENU");
        BOTONMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONMENUActionPerformed(evt);
            }
        });

        campsala.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campsala.setForeground(new java.awt.Color(255, 0, 0));

        campnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campnombre.setForeground(new java.awt.Color(255, 0, 0));

        campdescrip.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campdescrip.setForeground(new java.awt.Color(255, 0, 0));

        camplocal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        camplocal.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(63, 63, 63)))
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idsala, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(descripcionsala)
                        .addComponent(localizacionsala, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(nombresala)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campsala)
                    .addComponent(campnombre)
                    .addComponent(campdescrip)
                    .addComponent(camplocal))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(botonaceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BOTONMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idsala, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campsala))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nombresala, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campnombre)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcionsala, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(campdescrip))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(localizacionsala, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(camplocal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOTONMENU)
                    .addComponent(botonaceptar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresalaActionPerformed

    private void botonaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonaceptarActionPerformed
        
String ida=idsala.getText();
String nombre=nombresala.getText();
String descrip=descripcionsala.getText();
String local=localizacionsala.getText();

String msj;
String nuevalinea="";
ManejoSallas ma=new ManejoSallas();

try
{
    if(crear==false)
    {
       msj= ma.GuardarDatos(ida,nombre,descrip,local);
    }
    else
    {
        nuevalinea=(ida+"; "+nombre+"; "+descrip+"; "+local);
        ma.ModificarDatos(nuevalinea,ida);
    }
    accion.setText("Guardando datos");

    
    Blanquear();
                
    
    
    
}catch(Exception e)
{
    System.out.println("ERROR"+e);
} 
          

    
    }//GEN-LAST:event_botonaceptarActionPerformed

    private void idsalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idsalaKeyTyped
char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_idsalaKeyTyped

    private void localizacionsalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localizacionsalaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_localizacionsalaKeyTyped

    private void BOTONMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONMENUActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BOTONMENUActionPerformed

    private void idsalaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idsalaKeyReleased
        // TODO add your handling code here:
        validar();
        int cod;
        boolean encontrado=false;

        cod=Integer.parseInt(idsala.getText());

        Scanner s;
        
        try {
            
            File f=new File("Salas.txt");
            
            if(!f.exists())
            {
                
                f.createNewFile();
            }
            s = new Scanner(f);
            //else
            
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        if(cod==Integer.parseInt(sl.next()))
                        {
                            nombresala.setText(sl.next());
                            descripcionsala.setText(sl.next());
                            localizacionsala.setText(sl.next());
                            
                            
                            encontrado=true;
                            crear = true;
                            //Satigualinea=(campoid.getText() + "; " + camponombre.getText() + "; " + campoapellido.getText() + "; " + campotel.getText() + "; " + campocorreo.getText());
                            accion.setText("Modificando...");
                        }
                        else
                        {  //Salida.setText("Este registro no existe");
                            nombresala.setText("");
                            descripcionsala.setText("");
                            localizacionsala.setText("");
                            
 
                            encontrado=false;
                            crear = false;
                            accion.setText("Creando...");
                        }
                    } // fin try
                    catch (Exception  e1)
                    {
                       // JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
                       
                    }
                } // fin while
            

            s.close();
        } // fin try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e);
        }
       
    }//GEN-LAST:event_idsalaKeyReleased

    private void localizacionsalaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localizacionsalaKeyReleased
        // TODO add your handling code here:
        validar();
 int cod;
        boolean encontrado=false;

        cod=Integer.parseInt(localizacionsala.getText());

        Scanner s;
        
        try {
            
            File f=new File("Localizacion.txt");
            
            if(!f.exists())
            {
                
                f.createNewFile();
            }
            s = new Scanner(f);
            //else
            
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        if(cod==Integer.parseInt(sl.next()))
                        {
             
                            localizacionsala.setText(sl.next());
                            
                       
                        }
                
                    } // fin try
                    catch (Exception  e1)
                    {
                       // JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e1);
                       
                    }
                } // fin while
            

            s.close();
        } // fin try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e);
        }
    }//GEN-LAST:event_localizacionsalaKeyReleased

    private void nombresalaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresalaKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_nombresalaKeyReleased

    private void descripcionsalaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionsalaKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_descripcionsalaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSalas().setVisible(true);
            }
        });
        
    }
        public void Blanquear()
        {
            nombresala.setText("");
            descripcionsala.setText("");
            localizacionsala.setText("");
            
        }
        
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONMENU;
    private javax.swing.JTextPane accion;
    private javax.swing.JButton botonaceptar;
    private javax.swing.JLabel campdescrip;
    private javax.swing.JLabel camplocal;
    private javax.swing.JLabel campnombre;
    private javax.swing.JLabel campsala;
    private javax.swing.JTextField descripcionsala;
    private javax.swing.JTextField idsala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localizacionsala;
    private javax.swing.JTextField nombresala;
    // End of variables declaration//GEN-END:variables
}
