/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author alex008c
 */
public class FrameHorarioActividad extends javax.swing.JFrame {

    /**
     * Creates new form FrameHorarioReserva
     */
    public FrameHorarioActividad() {
        initComponents();
    }
    Boolean crear = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        identrenador = new javax.swing.JLabel();
        nombreentrenador = new javax.swing.JLabel();
        apellidoentrenador = new javax.swing.JLabel();
        telentrenador = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        campoid = new javax.swing.JTextField();
        campodia = new javax.swing.JTextField();
        campohora = new javax.swing.JTextField();
        campoidact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        estatus = new javax.swing.JTextPane();
        limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campominuto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GYM");

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Horarios de Actividades");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(25, 25, 25));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));

        identrenador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        identrenador.setForeground(new java.awt.Color(204, 204, 204));
        identrenador.setText("ID Actividad ");

        nombreentrenador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nombreentrenador.setForeground(new java.awt.Color(204, 204, 204));
        nombreentrenador.setText("Dia Actividad");

        apellidoentrenador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        apellidoentrenador.setForeground(new java.awt.Color(204, 204, 204));
        apellidoentrenador.setText("Hora Actividad");

        telentrenador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        telentrenador.setForeground(new java.awt.Color(204, 204, 204));
        telentrenador.setText(" ID Actividad");

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(204, 204, 204));
        menu.setText("Menu");
        menu.setMaximumSize(new java.awt.Dimension(96, 35));
        menu.setMinimumSize(new java.awt.Dimension(96, 35));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        registrar.setBackground(new java.awt.Color(0, 0, 0));
        registrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registrar.setForeground(new java.awt.Color(204, 204, 204));
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        campoid.setBackground(new java.awt.Color(204, 204, 204));
        campoid.setForeground(new java.awt.Color(0, 0, 0));
        campoid.setCaretColor(new java.awt.Color(0, 0, 0));
        campoid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoidKeyReleased(evt);
            }
        });

        campodia.setBackground(new java.awt.Color(204, 204, 204));
        campodia.setCaretColor(new java.awt.Color(0, 0, 0));

        campohora.setBackground(new java.awt.Color(204, 204, 204));
        campohora.setCaretColor(new java.awt.Color(0, 0, 0));
        campohora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campohoraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campohoraKeyTyped(evt);
            }
        });

        campoidact.setBackground(new java.awt.Color(204, 204, 204));
        campoidact.setCaretColor(new java.awt.Color(0, 0, 0));
        campoidact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoidactKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Estatus");

        estatus.setBackground(new java.awt.Color(51, 51, 51));
        estatus.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        estatus.setForeground(new java.awt.Color(51, 51, 51));
        estatus.setCaretColor(new java.awt.Color(102, 102, 102));
        estatus.setEnabled(false);
        jScrollPane1.setViewportView(estatus);

        limpiar.setBackground(new java.awt.Color(0, 0, 0));
        limpiar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        limpiar.setForeground(new java.awt.Color(204, 204, 204));
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("H");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("M");

        campominuto.setBackground(new java.awt.Color(204, 204, 204));
        campominuto.setCaretColor(new java.awt.Color(0, 0, 0));
        campominuto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campominutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campominutoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Format 24");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(identrenador)
                    .addComponent(nombreentrenador)
                    .addComponent(telentrenador)
                    .addComponent(apellidoentrenador)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campohora, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campominuto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campodia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(campoid, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoidact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(registrar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(limpiar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identrenador)
                    .addComponent(campoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreentrenador)
                    .addComponent(campodia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoentrenador)
                    .addComponent(campohora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(campominuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telentrenador)
                    .addComponent(campoidact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
    int cod;
        boolean encontrado=false;
        cod=Integer.parseInt(campoidact.getText());

        Scanner s;
        try {
            File f=new File("Actividades.txt");
            
            
            s = new Scanner(f);
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        if(cod!=Integer.parseInt(sl.next()))
                        { 
                            campoidact.setText("ID Actividad no existe");
                            encontrado=false;
                        }
                        
                    } // fin try
                    catch (Exception  e1)
                    {
                       JOptionPane.showMessageDialog(null,"El archivo de ID actividades no existe.");
                       
                    }
                } // fin while
            s.close();
        } // fin try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"El archivo Actividades no existe. ");
        }
        
        
     //Parte en que inicia el guardado o modificacion   
    String id="";
    String dia="";
    String hora="";
    String minuto="";
    String idact="";
    
    ManejoHorarioActividad mh=new ManejoHorarioActividad();
        id=campoid.getText();
        dia=campodia.getText();
        hora=campohora.getText();
        minuto=campominuto.getText();
        idact=campoidact.getText();
        
        String Snuevalinea="";
        try {

            if (crear==false)
            {
                mh.GuardarDatos (id, dia, hora, minuto, idact);
            }
            else
            {
                Snuevalinea=(id + "; " + dia + "; " + hora + "; " + minuto + "; " + idact);
                mh.ModificaDatos(Snuevalinea,id);
            }
            campoid.setText("");
            campodia.setText("");
            campohora.setText("");
            campominuto.setText("");
            campoidact.setText("");
            estatus.setText("");

        } // fin try
        
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void campoidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoidKeyReleased
       int cod;
        boolean encontrado=false;

        cod=Integer.parseInt(campoid.getText());

        Scanner s;
        try {
            File f=new File("HorarioActividades.txt");
            
            if(!f.exists())
            {
                f.createNewFile();
                estatus.setText("Creando...");
            }
            s = new Scanner(f);
                while (s.hasNextLine() && !encontrado)
                {
                    String linea = s.nextLine();

                    Scanner sl = new Scanner(linea);

                    sl.useDelimiter("\\s*;\\s*");
                    try {
                        if(cod==Integer.parseInt(sl.next()))
                        {
                            campodia.setText(sl.next());
                            campohora.setText(sl.next());
                            campominuto.setText(sl.next());
                            campoidact.setText(sl.next());
                            encontrado=true;
                            crear = true;
                            estatus.setText("Modificando...");
                        }
                        else
                        { 
                            campodia.setText("");
                            campohora.setText("");
                            campominuto.setText("");
                            campoidact.setText("");
                            estatus.setText(""); 
                            encontrado=false;
                            crear = false;
                            estatus.setText("Creando...");
                        }
                        
                    } // fin try
                    catch (Exception  e1)
                    {
                       JOptionPane.showMessageDialog(null,"Error al leer Archivo   " + e1);
                       
                    }
                } // fin while
            s.close();
        } // fin try
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al leer Archivo " + e);
        }
       
    }//GEN-LAST:event_campoidKeyReleased

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        campoid.setText("");
        campodia.setText("");
        campohora.setText("");
        campominuto.setText("");
        campoidact.setText("");
        estatus.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void campohoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campohoraKeyTyped
       char c=evt.getKeyChar();
       if(c<'0' || c>'9')evt.consume();
       
    }//GEN-LAST:event_campohoraKeyTyped

    private void campominutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campominutoKeyTyped
        char c=evt.getKeyChar();
       if(c<'0' || c>'9')evt.consume();
       
    }//GEN-LAST:event_campominutoKeyTyped

    private void campohoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campohoraKeyReleased
       int hora=Integer.parseInt(campohora.getText());
       if(hora<0 || hora > 23){
           campohora.setText("");
       }  
    }//GEN-LAST:event_campohoraKeyReleased

    private void campominutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campominutoKeyReleased
       int hora=Integer.parseInt(campominuto.getText());
       if(hora<0 || hora > 59){
          campominuto.setText("");
        }
    }//GEN-LAST:event_campominutoKeyReleased

    private void campoidactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoidactKeyReleased
        
    }//GEN-LAST:event_campoidactKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHorarioActividad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHorarioActividad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoentrenador;
    private javax.swing.JTextField campodia;
    private javax.swing.JTextField campohora;
    private javax.swing.JTextField campoid;
    private javax.swing.JTextField campoidact;
    private javax.swing.JTextField campominuto;
    private javax.swing.JTextPane estatus;
    private javax.swing.JLabel identrenador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton menu;
    private javax.swing.JLabel nombreentrenador;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel telentrenador;
    // End of variables declaration//GEN-END:variables
}
